print("because letter case is same")
print("sachin"=="sachin")
print("because letter case is different")
print("Sachin"=="sachin")
print("because letter case is different")
print("sachin"!="Sachin")
print("because uppercase letters are considered smaller than the lowercase letters due to their ASCII values.")
print("sachin">"SACHIN")
print("5611">"1156")
